use crate::channel::IncomingMessage;
use crate::config::Config;
use std::path::Path;

use super::doctor::{wx_cli_capture_summary, wx_cli_doctor_blockers, wx_cli_doctor_warnings};
use super::dry_run::wx_cli_dry_run_item;
use super::support::wx_cli_group_reply_candidate_message_ids;
use super::support::wx_cli_reply_candidate_message_ids;

pub fn wx_cli_formal_test_plan(
    config: &Config,
    config_path: &Path,
    capture_file: &Path,
    message_id: Option<&str>,
    chat_id: Option<&str>,
    text: &str,
    messages: Option<&[IncomingMessage]>,
) -> serde_json::Value {
    let config_path = config_path.display().to_string();
    let capture_file = capture_file.display().to_string();
    let reply_candidates = match messages {
        Some(messages) => wx_cli_reply_candidate_message_ids(config, messages),
        None => Vec::new(),
    };
    let group_reply_candidates = match messages {
        Some(messages) => wx_cli_group_reply_candidate_message_ids(config, messages),
        None => Vec::new(),
    };
    let selected_message_id = select_formal_test_message_id(message_id, &group_reply_candidates);
    let selected_chat_id =
        select_formal_test_chat_id(config, chat_id, messages, selected_message_id.value);
    let mut blockers = wx_cli_doctor_blockers(config);
    blockers.extend(wx_cli_test_plan_capture_blockers(
        messages,
        message_id,
        &group_reply_candidates,
    ));
    blockers.extend(wx_cli_test_plan_message_blockers(
        messages,
        &selected_message_id,
    ));
    blockers.extend(wx_cli_test_plan_chat_blockers(&selected_chat_id));
    let warnings = wx_cli_doctor_warnings(config, messages);
    let capture = messages.map(|messages| wx_cli_capture_summary(config, messages, 10));
    let selected_message =
        selected_formal_test_message_summary(config, messages, selected_message_id.value);
    blockers.extend(wx_cli_test_plan_selected_message_blockers(
        &selected_message,
    ));
    let steps = wx_cli_formal_test_steps(
        &config_path,
        &capture_file,
        selected_message_id.value,
        selected_chat_id.value,
        text,
        messages.is_some(),
    );

    serde_json::json!({
        "ok": blockers.is_empty(),
        "blockers": blockers,
        "warnings": warnings,
        "capture": capture,
        "reply_candidate_message_ids": reply_candidates,
        "group_reply_candidate_message_ids": group_reply_candidates,
        "config_path": config_path,
        "capture_file": capture_file,
        "message_id": selected_message_id.value,
        "message_id_source": selected_message_id.source,
        "selected_message": selected_message,
        "chat_id": selected_chat_id.value,
        "chat_id_source": selected_chat_id.source,
        "text": text,
        "steps": steps
    })
}

pub fn wx_cli_formal_test_plan_shell_script(plan: &serde_json::Value) -> String {
    let mut script = String::from("#!/usr/bin/env bash\nset -euo pipefail\n\n");
    script.push_str("# Generated by `qunmind wx-cli test-plan --shell`.\n");
    script.push_str("# Real-send steps are commented and require manual confirmation.\n\n");

    push_shell_plan_metadata(&mut script, plan);
    push_shell_plan_selected_message(&mut script, plan);
    push_shell_plan_blockers(&mut script, plan);
    push_shell_plan_warnings(&mut script, plan);
    push_shell_plan_steps(&mut script, plan);

    script
}

struct FormalTestMessageId<'a> {
    value: &'a str,
    source: &'static str,
}

impl FormalTestMessageId<'_> {
    fn is_placeholder(&self) -> bool {
        self.source == "placeholder"
    }
}

struct FormalTestChatId<'a> {
    value: &'a str,
    source: &'static str,
}

fn push_shell_plan_metadata(script: &mut String, plan: &serde_json::Value) {
    for (label, key) in [
        ("config", "config_path"),
        ("capture", "capture_file"),
        ("message_id", "message_id"),
        ("chat_id", "chat_id"),
    ] {
        if let Some(value) = json_string(plan, key) {
            script.push_str("# ");
            script.push_str(label);
            script.push_str(": ");
            script.push_str(value);
            script.push('\n');
        }
    }
    script.push('\n');
}

fn push_shell_plan_selected_message(script: &mut String, plan: &serde_json::Value) {
    let Some(message) = plan
        .get("selected_message")
        .filter(|message| !message.is_null())
    else {
        return;
    };

    script.push_str("# Selected message:\n");
    for (label, key) in [
        ("message_id", "message_id"),
        ("chat_id", "chat_id"),
        ("from", "from"),
        ("reason", "reason"),
    ] {
        if let Some(value) = json_string(message, key) {
            push_shell_comment_value(script, label, value);
        }
    }
    if let Some(value) = json_string(message, "text_preview") {
        push_shell_comment_value(script, "text_preview", value);
    }
    script.push('\n');
}

fn push_shell_comment_value(script: &mut String, label: &str, value: &str) {
    script.push_str("# ");
    script.push_str(label);
    script.push_str(": ");
    script.push_str(&single_line_comment_value(value));
    script.push('\n');
}

fn single_line_comment_value(value: &str) -> String {
    value
        .chars()
        .map(|ch| match ch {
            '\n' | '\r' => ' ',
            _ => ch,
        })
        .collect()
}

fn push_shell_plan_blockers(script: &mut String, plan: &serde_json::Value) {
    let blockers = json_string_array(plan, "blockers");
    if blockers.is_empty() {
        return;
    }

    script.push_str("# Blockers:\n");
    for blocker in blockers {
        script.push_str("# - ");
        script.push_str(blocker);
        script.push('\n');
    }
    script.push_str("echo 'QunMind wx-cli test plan is not ready; fix blockers first.' >&2\n");
    script.push_str("exit 1\n\n");
}

fn push_shell_plan_warnings(script: &mut String, plan: &serde_json::Value) {
    let warnings = json_string_array(plan, "warnings");
    if warnings.is_empty() {
        return;
    }

    script.push_str("# Warnings:\n");
    for warning in warnings {
        script.push_str("# - ");
        script.push_str(warning);
        script.push('\n');
    }
    script.push('\n');
}

fn push_shell_plan_steps(script: &mut String, plan: &serde_json::Value) {
    let Some(steps) = plan.get("steps").and_then(|steps| steps.as_array()) else {
        script.push_str("echo 'QunMind wx-cli test plan has no steps.' >&2\n");
        script.push_str("exit 1\n");
        return;
    };

    for step in steps {
        let name = json_string(step, "name").map_or("unnamed_step", std::convert::identity);
        let safe_to_send = matches!(
            step.get("safe_to_send").and_then(|value| value.as_bool()),
            Some(true)
        );
        let Some(command) = shell_command_from_step(step) else {
            script.push_str("# ");
            script.push_str(name);
            script.push_str(": skipped because command is not renderable\n");
            continue;
        };

        script.push_str("# ");
        script.push_str(name);
        script.push('\n');
        if safe_to_send {
            script.push_str("# REAL_SEND: review the dry-run output before uncommenting.\n");
            script.push_str("# ");
            script.push_str(&command);
            script.push('\n');
        } else {
            script.push_str(&command);
            script.push('\n');
        }
        script.push('\n');
    }
}

fn shell_command_from_step(step: &serde_json::Value) -> Option<String> {
    let command = step.get("command")?.as_array()?;
    let mut parts = Vec::new();
    for item in command {
        let text = item.as_str()?;
        parts.push(shell_quote(text));
    }
    Some(parts.join(" "))
}

fn shell_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".to_string();
    }

    let escaped = value.replace('\'', "'\"'\"'");
    format!("'{escaped}'")
}

fn json_string<'a>(value: &'a serde_json::Value, key: &str) -> Option<&'a str> {
    value.get(key).and_then(|value| value.as_str())
}

fn json_string_array<'a>(value: &'a serde_json::Value, key: &str) -> Vec<&'a str> {
    match value.get(key).and_then(|value| value.as_array()) {
        Some(items) => items.iter().filter_map(|item| item.as_str()).collect(),
        None => Vec::new(),
    }
}

fn wx_cli_formal_test_steps(
    config_path: &str,
    capture_file: &str,
    message_id: &str,
    chat_id: &str,
    text: &str,
    has_captured_input: bool,
) -> Vec<serde_json::Value> {
    let mut steps = vec![serde_json::json!({
        "name": "doctor_config",
        "safe_to_send": false,
        "command": wx_cli_cargo_command(config_path, &["doctor"])
    })];

    if !has_captured_input {
        steps.push(serde_json::json!({
            "name": "capture_once",
            "safe_to_send": false,
            "command": wx_cli_cargo_command(config_path, &["capture", "--output", capture_file])
        }));
    }

    steps.extend([
        serde_json::json!({
            "name": "doctor_capture",
            "safe_to_send": false,
            "command": wx_cli_cargo_command(config_path, &["doctor", "--input", capture_file])
        }),
        serde_json::json!({
            "name": "dry_run_selected_message",
            "safe_to_send": false,
            "command": wx_cli_cargo_command(config_path, &["dry-run", "--input", capture_file, "--message-id", message_id])
        }),
        serde_json::json!({
            "name": "handle_once_no_send",
            "safe_to_send": false,
            "command": wx_cli_cargo_command(config_path, &["handle-once", "--input", capture_file, "--message-id", message_id, "--limit", "1", "--no-send"])
        }),
        serde_json::json!({
            "name": "send_dry_run",
            "safe_to_send": false,
            "command": wx_cli_cargo_command(config_path, &["send", "--chat-id", chat_id, "--text", text, "--dry-run"])
        }),
        serde_json::json!({
            "name": "send_diagnostic_text",
            "safe_to_send": true,
            "command": wx_cli_cargo_command(config_path, &["send", "--chat-id", chat_id, "--text", text])
        }),
        serde_json::json!({
            "name": "handle_once_real_send",
            "safe_to_send": true,
            "command": wx_cli_cargo_command(config_path, &["handle-once", "--input", capture_file, "--message-id", message_id, "--limit", "1"])
        }),
    ]);

    steps
}

fn selected_formal_test_message_summary(
    config: &Config,
    messages: Option<&[IncomingMessage]>,
    message_id: &str,
) -> serde_json::Value {
    let Some(messages) = messages else {
        return serde_json::Value::Null;
    };
    let mut matching = messages
        .iter()
        .filter(|message| message.message_id == message_id);
    let Some(message) = matching.next() else {
        return serde_json::Value::Null;
    };
    if matching.next().is_some() {
        return serde_json::Value::Null;
    }

    wx_cli_dry_run_item(config, message)
}

fn wx_cli_cargo_command(config_path: &str, args: &[&str]) -> Vec<String> {
    let mut command = vec![
        "cargo".to_string(),
        "run".to_string(),
        "--".to_string(),
        "--config".to_string(),
        config_path.to_string(),
        "wx-cli".to_string(),
    ];
    command.extend(args.iter().map(|arg| (*arg).to_string()));
    command
}

fn select_formal_test_message_id<'a>(
    message_id: Option<&'a str>,
    reply_candidates: &'a [String],
) -> FormalTestMessageId<'a> {
    if let Some(message_id) = message_id.filter(|message_id| !message_id.trim().is_empty()) {
        return FormalTestMessageId {
            value: message_id,
            source: "explicit",
        };
    }

    match reply_candidates {
        [message_id] => FormalTestMessageId {
            value: message_id.as_str(),
            source: "single_group_reply_candidate",
        },
        _ => FormalTestMessageId {
            value: "<message_id_from_reply_candidate_message_ids>",
            source: "placeholder",
        },
    }
}

fn select_formal_test_chat_id<'a>(
    config: &'a Config,
    chat_id: Option<&'a str>,
    messages: Option<&'a [IncomingMessage]>,
    selected_message_id: &str,
) -> FormalTestChatId<'a> {
    if let Some(chat_id) = chat_id.filter(|chat_id| !chat_id.trim().is_empty()) {
        return FormalTestChatId {
            value: chat_id,
            source: "explicit",
        };
    }

    let configured_chat_id = config.wx_cli.group_chat_id.trim();
    if !configured_chat_id.is_empty() {
        return FormalTestChatId {
            value: configured_chat_id,
            source: "config",
        };
    }

    let selected_message = match messages {
        Some(messages) => messages
            .iter()
            .find(|message| message.message_id == selected_message_id),
        None => None,
    };
    if let Some(message) = selected_message {
        return FormalTestChatId {
            value: message.chat_id.as_str(),
            source: "selected_message",
        };
    }

    FormalTestChatId {
        value: "<test_chat_id>",
        source: "placeholder",
    }
}

fn wx_cli_test_plan_capture_blockers(
    messages: Option<&[IncomingMessage]>,
    message_id: Option<&str>,
    reply_candidates: &[String],
) -> Vec<&'static str> {
    let mut blockers = Vec::new();
    let Some(messages) = messages else {
        return blockers;
    };

    if let Some(message_id) = message_id.filter(|message_id| !message_id.trim().is_empty()) {
        let matched_count = messages
            .iter()
            .filter(|message| message.message_id == message_id)
            .count();
        if matched_count == 0 {
            blockers.push("selected_message_id_not_found_in_capture");
        } else if matched_count > 1 {
            blockers.push("selected_message_id_not_unique_in_capture");
        }
    } else if reply_candidates.len() != 1 {
        blockers.push("capture_requires_explicit_message_id");
    }

    blockers
}

fn wx_cli_test_plan_message_blockers(
    messages: Option<&[IncomingMessage]>,
    message_id: &FormalTestMessageId<'_>,
) -> Vec<&'static str> {
    if messages.is_none() && message_id.is_placeholder() {
        return vec!["test_message_id_required"];
    }

    Vec::new()
}

fn wx_cli_test_plan_chat_blockers(chat_id: &FormalTestChatId<'_>) -> Vec<&'static str> {
    if chat_id.source == "placeholder" {
        return vec!["test_chat_id_required"];
    }

    Vec::new()
}

fn wx_cli_test_plan_selected_message_blockers(
    selected_message: &serde_json::Value,
) -> Vec<&'static str> {
    if matches!(
        selected_message
            .get("is_group")
            .and_then(|value| value.as_bool()),
        Some(false)
    ) {
        return vec!["selected_message_not_group"];
    }

    if matches!(
        selected_message
            .get("would_reply")
            .and_then(|value| value.as_bool()),
        Some(false)
    ) {
        return vec!["selected_message_would_not_reply"];
    }

    Vec::new()
}
